--- Req 9
SELECT u.IDUSUARIO, u.NOMBRE, u.EMAIL
FROM USUARIOS u INNER JOIN SILLAS s ON s.USUARIOS_IDUSUARIO = u.IDUSUARIO
	INNER JOIN FUNCIONES f ON f.IDFUNCION = s.FUNCIONES_IDFUNCION
	INNER JOIN ESPECTACULOS e ON e.NOMBRE = f.ESPECTACULOS_NOMBRE
	INNER JOIN COMPANHIAS_ESPECTACULOS ce ON ce.ESPECTACULOS_NOMBRE = e.NOMBRE
WHERE s.ASISTIO = '1'
	AND ce.COMPANHIAS_NOMBRE = :nombreCompanhiaParam
	AND f.FECHAR BETWEEN :fechaParam1 AND :fechaParam2;

--- Req 10
SELECT u.IDUSUARIO, u.NOMBRE, u.EMAIL
FROM USUARIOS u INNER JOIN SILLAS s ON s.USUARIOS_IDUSUARIO = u.IDUSUARIO
	INNER JOIN FUNCIONES f ON f.IDFUNCION = s.FUNCIONES_IDFUNCION
	INNER JOIN ESPECTACULOS e ON e.NOMBRE = f.ESPECTACULOS_NOMBRE
	INNER JOIN COMPANHIAS_ESPECTACULOS ce ON ce.ESPECTACULOS_NOMBRE = e.NOMBRE
WHERE s.ASISTIO = '0'
	AND ce.COMPANHIAS_NOMBRE = :nombreCompanhiaParam
	AND f.FECHAR BETWEEN :fechaParam1 AND :fechaParam2;

--- Req 11
SELECT f.ESPECTACULOS_nombre, f.fechaR, SITIOS.NOMBRES, COUNT(*) AS boletas_vendidas, COUNT(s.USUARIOS_idUsuario) AS usuarios_registrados
FROM FUNCIONES f INNER JOIN SILLAS s ON f.IDFUNCION = s.FUNCIONES_IDFUNCION
	INNER JOIN ESPECTACULOS e ON f.ESPECTACULOS_NOMBRE = e.NOMBRE
	INNER JOIN LOCALIDADES l ON s.LOCALIDADES_IDLOCALIDAD = l.IDLOCALIDAD
	INNER JOIN SITIOS ON SITIOS.IDSITIO = f.SITIOS_IDSITIO
WHERE s.DISPONIBLE = '0'
GROUP BY f.ESPECTACULOS_nombre, f.fechaR, SITIOS.NOMBRES;

--- Req 12
